


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "jg_account";


ALTER SCHEMA "jg_account" OWNER TO "postgres";


CREATE TYPE "jg_account"."user_role" AS ENUM (
    'user',
    'admin',
    'super_admin'
);


ALTER TYPE "jg_account"."user_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "jg_account"."count_my_sessions"() RETURNS integer
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  SELECT count(*)::integer
  FROM auth.sessions s
  WHERE s.user_id = auth.uid()
    AND (s.not_after IS NULL OR s.not_after > now());
$$;


ALTER FUNCTION "jg_account"."count_my_sessions"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "jg_account"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into jg_account.profiles (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
exception when others then
  raise warning 'jg_account.handle_new_user failed for user %: %', new.id, sqlerrm;
  return new;
end;
$$;


ALTER FUNCTION "jg_account"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "jg_account"."handle_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "jg_account"."handle_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "jg_account"."is_admin"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM jg_account.profiles
    WHERE user_id = auth.uid()
      AND role IN ('admin', 'super_admin')
  );
END;
$$;


ALTER FUNCTION "jg_account"."is_admin"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "jg_account"."profiles" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "first_name" "text" DEFAULT ''::"text" NOT NULL,
    "last_name" "text" DEFAULT ''::"text" NOT NULL,
    "avatar_url" "text",
    "role" "jg_account"."user_role" DEFAULT 'user'::"jg_account"."user_role" NOT NULL,
    "terms_accepted" boolean DEFAULT false NOT NULL,
    "terms_accepted_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "avatar_mode" "text" DEFAULT 'provider'::"text" NOT NULL,
    "avatar_provider" "text",
    "avatar_storage_path" "text",
    "avatar_updated_at" timestamp with time zone,
    CONSTRAINT "profiles_avatar_mode_check" CHECK (("avatar_mode" = ANY (ARRAY['provider'::"text", 'upload'::"text", 'initials'::"text"]))),
    CONSTRAINT "profiles_avatar_upload_path_check" CHECK ((("avatar_mode" <> 'upload'::"text") OR (NULLIF("btrim"("avatar_storage_path"), ''::"text") IS NOT NULL)))
);


ALTER TABLE "jg_account"."profiles" OWNER TO "postgres";


ALTER TABLE "jg_account"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "jg_account"."profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "jg_account"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "jg_account"."profiles"
    ADD CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id");



CREATE INDEX "idx_profiles_user_id" ON "jg_account"."profiles" USING "btree" ("user_id");



CREATE OR REPLACE TRIGGER "set_updated_at" BEFORE UPDATE ON "jg_account"."profiles" FOR EACH ROW EXECUTE FUNCTION "jg_account"."handle_updated_at"();



ALTER TABLE ONLY "jg_account"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admins can read all profiles" ON "jg_account"."profiles" FOR SELECT TO "authenticated" USING ("jg_account"."is_admin"());



CREATE POLICY "Super admins can delete profiles" ON "jg_account"."profiles" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "jg_account"."profiles" "profiles_1"
  WHERE (("profiles_1"."user_id" = "auth"."uid"()) AND ("profiles_1"."role" = 'super_admin'::"jg_account"."user_role")))));



CREATE POLICY "Super admins can insert profiles" ON "jg_account"."profiles" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "jg_account"."profiles" "profiles_1"
  WHERE (("profiles_1"."user_id" = "auth"."uid"()) AND ("profiles_1"."role" = 'super_admin'::"jg_account"."user_role")))));



CREATE POLICY "Super admins can update any profile" ON "jg_account"."profiles" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "jg_account"."profiles" "profiles_1"
  WHERE (("profiles_1"."user_id" = "auth"."uid"()) AND ("profiles_1"."role" = 'super_admin'::"jg_account"."user_role")))));



CREATE POLICY "Users can read own profile" ON "jg_account"."profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own profile" ON "jg_account"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK ((("auth"."uid"() = "user_id") AND ("role" = ( SELECT "profiles_1"."role"
   FROM "jg_account"."profiles" "profiles_1"
  WHERE ("profiles_1"."user_id" = "auth"."uid"())))));



ALTER TABLE "jg_account"."profiles" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "jg_account" TO "anon";
GRANT USAGE ON SCHEMA "jg_account" TO "authenticated";
GRANT USAGE ON SCHEMA "jg_account" TO "service_role";



REVOKE ALL ON FUNCTION "jg_account"."count_my_sessions"() FROM PUBLIC;
GRANT ALL ON FUNCTION "jg_account"."count_my_sessions"() TO "authenticated";
GRANT ALL ON FUNCTION "jg_account"."count_my_sessions"() TO "service_role";



GRANT ALL ON FUNCTION "jg_account"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "jg_account"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "jg_account"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "jg_account"."handle_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "jg_account"."handle_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "jg_account"."handle_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "jg_account"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "jg_account"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "jg_account"."is_admin"() TO "service_role";



GRANT ALL ON TABLE "jg_account"."profiles" TO "anon";
GRANT ALL ON TABLE "jg_account"."profiles" TO "authenticated";
GRANT ALL ON TABLE "jg_account"."profiles" TO "service_role";



GRANT USAGE ON SEQUENCE "jg_account"."profiles_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "jg_account"."profiles_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "jg_account"."profiles_id_seq" TO "service_role";
