import {
  Key,
  Hash,
  Lock,
  Fingerprint,
  Shield,
  FileLock,
  Eye,
  Calendar,
  Calculator,
  Type,
  Palette,
  Code,
  Globe,
  FileText,
  Link,
  Search,
  Zap,
  Network,
  QrCode,
  Camera,
  GitBranch,
  Clock,
  Thermometer,
  Gauge,
  FileCode,
  Mail,
  User,
  Settings,
  Wifi,
  Image,
  Database,
  Server,
  Globe2,
  FileJson,
  FileCode2,
  FileType,
  Text,
  KeyRound,
  Phone,
  CreditCard,
  Regex,
  Timer,
  BarChart3,
  Smile,
  EyeOff,
  Diff,
  FileCheck,
  Info,
  ShieldCheck,
  Code2,
  List,
  RefreshCw,
  Keyboard,
} from "lucide-react"

export interface Tool {
  id: string
  title: string
  description: string
  icon: React.ElementType
  path: string
}

export interface ToolCategory {
  id: string
  title: string
  icon: React.ElementType
  tools: Tool[]
}

export const toolCategories: ToolCategory[] = [
  {
    id: "generators",
    title: "Generators",
    icon: Zap,
    tools: [
      {
        id: "token-generator",
        title: "Token Generator",
        description: "Generate random string with the chars you want, uppercase or lowercase letters, numbers and/or symbols.",
        icon: Key,
        path: "/generators/token-generator",
      },
      {
        id: "uuid-generator",
        title: "UUID Generator",
        description: "A Universally Unique Identifier (UUID) is a 128-bit number used to identify information in computer systems.",
        icon: Fingerprint,
        path: "/generators/uuid-generator",
      },
      {
        id: "ulid-generator",
        title: "ULID Generator",
        description: "Generate random Universally Unique Lexicographically Sortable Identifier (ULID).",
        icon: Fingerprint,
        path: "/generators/ulid-generator",
      },
      {
        id: "bip39-generator",
        title: "BIP39 Passphrase Generator",
        description: "Generate a BIP39 passphrase from an existing or random mnemonic, or get the mnemonic from the passphrase.",
        icon: KeyRound,
        path: "/generators/bip39-generator",
      },
      {
        id: "rsa-key-generator",
        title: "RSA Key Pair Generator",
        description: "Generate a new random RSA private and public pem certificate key pair.",
        icon: Key,
        path: "/generators/rsa-key-generator",
      },
      {
        id: "otp-generator",
        title: "OTP Code Generator",
        description: "Generate and validate time-based OTP (one time password) for multi-factor authentication.",
        icon: ShieldCheck,
        path: "/generators/otp-generator",
      },
      {
        id: "random-port-generator",
        title: "Random Port Generator",
        description: "Generate random port numbers outside of the range of 'known' ports (0-1023).",
        icon: Network,
        path: "/generators/random-port-generator",
      },
      {
        id: "mac-generator",
        title: "MAC Address Generator",
        description: "Enter the quantity and prefix. MAC addresses will be generated in your chosen case.",
        icon: Network,
        path: "/generators/mac-generator",
      },
      {
        id: "ipv6-ula-generator",
        title: "IPv6 ULA Generator",
        description: "Generate your own local, non-routable IP addresses for your network according to RFC4193.",
        icon: Network,
        path: "/generators/ipv6-ula-generator",
      },
    ],
  },
  {
    id: "hash-encryption",
    title: "Hash & Encryption",
    icon: Lock,
    tools: [
      {
        id: "hash-text",
        title: "Hash Text",
        description: "Hash a text string using the function you need : MD5, SHA1, SHA256, SHA224, SHA512, SHA384, SHA3 or RIPEMD160.",
        icon: Hash,
        path: "/hash-encryption/hash-text",
      },
      {
        id: "bcrypt",
        title: "Bcrypt",
        description: "Hash and compare text string using bcrypt. Bcrypt is a password-hashing function based on the Blowfish cipher.",
        icon: Shield,
        path: "/hash-encryption/bcrypt",
      },
      {
        id: "encrypt-decrypt",
        title: "Encrypt / Decrypt Text",
        description: "Encrypt clear text and decrypt ciphertext using crypto algorithms like AES, TripleDES, Rabbit or RC4.",
        icon: FileLock,
        path: "/hash-encryption/encrypt-decrypt",
      },
      {
        id: "hmac-generator",
        title: "HMAC Generator",
        description: "Computes a hash-based message authentication code (HMAC) using a secret key and your favorite hashing function.",
        icon: Hash,
        path: "/hash-encryption/hmac-generator",
      },
      {
        id: "password-strength",
        title: "Password Strength Analyser",
        description: "Discover the strength of your password with this client-side-only password strength analyser and crack time estimation tool.",
        icon: Eye,
        path: "/hash-encryption/password-strength",
      },
    ],
  },
  {
    id: "converters",
    title: "Converters",
    icon: RefreshCw,
    tools: [
      {
        id: "date-time-converter",
        title: "Date-Time Converter",
        description: "Convert date and time into the various different formats.",
        icon: Calendar,
        path: "/converters/date-time-converter",
      },
      {
        id: "integer-base-converter",
        title: "Integer Base Converter",
        description: "Convert a number between different bases (decimal, hexadecimal, binary, octal, base64, ...).",
        icon: Calculator,
        path: "/converters/integer-base-converter",
      },
      {
        id: "roman-numeral-converter",
        title: "Roman Numeral Converter",
        description: "Convert Roman numerals to numbers and convert numbers to Roman numerals.",
        icon: Type,
        path: "/converters/roman-numeral-converter",
      },
      {
        id: "base64-encoder-decoder",
        title: "Base64 String Encoder/Decoder",
        description: "Simply encode and decode strings into their base64 representation.",
        icon: Code,
        path: "/converters/base64-encoder-decoder",
      },
      {
        id: "base64-file-converter",
        title: "Base64 File Converter",
        description: "Convert a string, file, or image into its base64 representation.",
        icon: FileCode,
        path: "/converters/base64-file-converter",
      },
      {
        id: "color-converter",
        title: "Color Converter",
        description: "Convert color between the different formats (hex, rgb, hsl and css name).",
        icon: Palette,
        path: "/converters/color-converter",
      },
      {
        id: "yaml-to-json",
        title: "YAML to JSON Converter",
        description: "Simply convert YAML to JSON with this online live converter.",
        icon: FileJson,
        path: "/converters/yaml-to-json",
      },
      {
        id: "yaml-to-toml",
        title: "YAML to TOML",
        description: "Parse and convert YAML to TOML.",
        icon: FileType,
        path: "/converters/yaml-to-toml",
      },
      {
        id: "json-to-yaml",
        title: "JSON to YAML Converter",
        description: "Simply convert JSON to YAML with this online live converter.",
        icon: FileJson,
        path: "/converters/json-to-yaml",
      },
      {
        id: "json-to-toml",
        title: "JSON to TOML",
        description: "Parse and convert JSON to TOML.",
        icon: FileType,
        path: "/converters/json-to-toml",
      },
      {
        id: "toml-to-json",
        title: "TOML to JSON",
        description: "Parse and convert TOML to JSON.",
        icon: FileJson,
        path: "/converters/toml-to-json",
      },
      {
        id: "toml-to-yaml",
        title: "TOML to YAML",
        description: "Parse and convert TOML to YAML.",
        icon: FileType,
        path: "/converters/toml-to-yaml",
      },
      {
        id: "xml-to-json",
        title: "XML to JSON",
        description: "Convert XML to JSON.",
        icon: FileJson,
        path: "/converters/xml-to-json",
      },
      {
        id: "json-to-xml",
        title: "JSON to XML",
        description: "Convert JSON to XML.",
        icon: FileCode2,
        path: "/converters/json-to-xml",
      },
      {
        id: "temperature-converter",
        title: "Temperature Converter",
        description: "Degrees temperature conversions for Kelvin, Celsius, Fahrenheit, Rankine, Delisle, Newton, Réaumur, and Rømer.",
        icon: Thermometer,
        path: "/converters/temperature-converter",
      },
    ],
  },
  {
    id: "text-tools",
    title: "Text Tools",
    icon: Type,
    tools: [
      {
        id: "case-converter",
        title: "Case Converter",
        description: "Transform the case of a string and choose between different formats.",
        icon: Type,
        path: "/text-tools/case-converter",
      },
      {
        id: "text-to-nato",
        title: "Text to NATO Alphabet",
        description: "Transform text into the NATO phonetic alphabet for oral transmission.",
        icon: Text,
        path: "/text-tools/text-to-nato",
      },
      {
        id: "text-to-ascii-binary",
        title: "Text to ASCII Binary",
        description: "Convert text to its ASCII binary representation and vice-versa.",
        icon: Code,
        path: "/text-tools/text-to-ascii-binary",
      },
      {
        id: "text-to-unicode",
        title: "Text to Unicode",
        description: "Parse and convert text to unicode and vice-versa.",
        icon: Type,
        path: "/text-tools/text-to-unicode",
      },
      {
        id: "list-converter",
        title: "List Converter",
        description: "This tool can process column-based data and apply various changes (transpose, add prefix and suffix, reverse list, sort list, lowercase values, truncate values) to each row.",
        icon: List,
        path: "/text-tools/list-converter",
      },
      {
        id: "slugify-string",
        title: "Slugify String",
        description: "Make a string url, filename and id safe.",
        icon: Link,
        path: "/text-tools/slugify-string",
      },
      {
        id: "text-statistics",
        title: "Text Statistics",
        description: "Get information about a text, the number of characters, the number of words, its size in bytes, ...",
        icon: BarChart3,
        path: "/text-tools/text-statistics",
      },
      {
        id: "text-diff",
        title: "Text Diff",
        description: "Compare two texts and see the differences between them.",
        icon: Diff,
        path: "/text-tools/text-diff",
      },
      {
        id: "numeronym-generator",
        title: "Numeronym Generator",
        description: 'A numeronym is a word where a number is used to form an abbreviation. For example, "i18n" is a numeronym of "internationalization".',
        icon: Hash,
        path: "/text-tools/numeronym-generator",
      },
      {
        id: "ascii-art-generator",
        title: "ASCII Art Text Generator",
        description: "Create ASCII art text with many fonts and styles.",
        icon: FileCode,
        path: "/text-tools/ascii-art-generator",
      },
      {
        id: "lorem-ipsum-generator",
        title: "Lorem Ipsum Generator",
        description: "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
        icon: FileText,
        path: "/text-tools/lorem-ipsum-generator",
      },
      {
        id: "string-obfuscator",
        title: "String Obfuscator",
        description: "Obfuscate a string (like a secret, an IBAN, or a token) to make it shareable and identifiable without revealing its content.",
        icon: EyeOff,
        path: "/text-tools/string-obfuscator",
      },
    ],
  },
  {
    id: "parsers-validators",
    title: "Parsers & Validators",
    icon: Search,
    tools: [
      {
        id: "url-parser",
        title: "URL Parser",
        description: "Parse a URL into its separate constituent parts (protocol, origin, params, port, username-password, ...).",
        icon: Link,
        path: "/parsers-validators/url-parser",
      },
      {
        id: "jwt-parser",
        title: "JWT Parser",
        description: "Parse and decode your JSON Web Token (jwt) and display its content.",
        icon: Key,
        path: "/parsers-validators/jwt-parser",
      },
      {
        id: "user-agent-parser",
        title: "User-Agent Parser",
        description: "Detect and parse Browser, Engine, OS, CPU, and Device type/model from an user-agent string.",
        icon: User,
        path: "/parsers-validators/user-agent-parser",
      },
      {
        id: "email-normalizer",
        title: "Email Normalizer",
        description: "Normalize email addresses to a standard format for easier comparison. Useful for deduplication and data cleaning.",
        icon: Mail,
        path: "/parsers-validators/email-normalizer",
      },
      {
        id: "phone-parser",
        title: "Phone Parser and Formatter",
        description: "Parse, validate and format phone numbers. Get information about the phone number, like the country code, type, etc.",
        icon: Phone,
        path: "/parsers-validators/phone-parser",
      },
      {
        id: "iban-validator",
        title: "IBAN Validator and Parser",
        description: "Validate and parse IBAN numbers. Check if an IBAN is valid and get information about it.",
        icon: CreditCard,
        path: "/parsers-validators/iban-validator",
      },
      {
        id: "pdf-signature-checker",
        title: "PDF Signature Checker",
        description: "Verify the signatures of a PDF file. A signed PDF file contains one or more signatures that may be used to determine whether the contents of the file have been altered since the file was signed.",
        icon: FileCheck,
        path: "/parsers-validators/pdf-signature-checker",
      },
    ],
  },
  {
    id: "formatters",
    title: "Formatters",
    icon: FileCode,
    tools: [
      {
        id: "json-prettify",
        title: "JSON Prettify and Format",
        description: "Prettify your JSON string into a friendly, human-readable format.",
        icon: FileJson,
        path: "/formatters/json-prettify",
      },
      {
        id: "json-minify",
        title: "JSON Minify",
        description: "Minify and compress your JSON by removing unnecessary whitespace.",
        icon: FileJson,
        path: "/formatters/json-minify",
      },
      {
        id: "sql-prettify",
        title: "SQL Prettify and Format",
        description: "Format and prettify your SQL queries online (it supports various SQL dialects).",
        icon: Database,
        path: "/formatters/sql-prettify",
      },
      {
        id: "xml-formatter",
        title: "XML Formatter",
        description: "Prettify your XML string into a friendly, human-readable format.",
        icon: FileCode2,
        path: "/formatters/xml-formatter",
      },
      {
        id: "yaml-prettify",
        title: "YAML Prettify and Format",
        description: "Prettify your YAML string into a friendly, human-readable format.",
        icon: FileType,
        path: "/formatters/yaml-prettify",
      },
    ],
  },
  {
    id: "code-dev-tools",
    title: "Code & Dev Tools",
    icon: Code2,
    tools: [
      {
        id: "git-cheatsheet",
        title: "Git Cheatsheet",
        description: "Git is a decentralized version management software. With this cheatsheet, you will have quick access to the most common git commands.",
        icon: GitBranch,
        path: "/code-dev-tools/git-cheatsheet",
      },
      {
        id: "regex-tester",
        title: "Regex Tester",
        description: "Test your regular expressions with sample text.",
        icon: Regex,
        path: "/code-dev-tools/regex-tester",
      },
      {
        id: "regex-cheatsheet",
        title: "Regex Cheatsheet",
        description: "Javascript Regex/Regular Expression cheatsheet.",
        icon: Regex,
        path: "/code-dev-tools/regex-cheatsheet",
      },
      {
        id: "chmod-calculator",
        title: "Chmod Calculator",
        description: "Compute your chmod permissions and commands with this online chmod calculator.",
        icon: Calculator,
        path: "/code-dev-tools/chmod-calculator",
      },
      {
        id: "docker-converter",
        title: "Docker Run to Docker Compose Converter",
        description: "Transforms 'docker run' commands into docker-compose files!",
        icon: Server,
        path: "/code-dev-tools/docker-converter",
      },
      {
        id: "http-status-codes",
        title: "HTTP Status Codes",
        description: "The list of all HTTP status codes, their name, and their meaning.",
        icon: Globe,
        path: "/code-dev-tools/http-status-codes",
      },
      {
        id: "json-diff",
        title: "JSON Diff",
        description: "Compare two JSON objects and get the differences between them.",
        icon: Diff,
        path: "/code-dev-tools/json-diff",
      },
      {
        id: "crontab-generator",
        title: "Crontab Generator",
        description: "Validate and generate crontab and get the human-readable description of the cron schedule.",
        icon: Clock,
        path: "/code-dev-tools/crontab-generator",
      },
      {
        id: "keycode-info",
        title: "Keycode Info",
        description: "Find the javascript keycode, code, location and modifiers of any pressed key.",
        icon: Keyboard,
        path: "/code-dev-tools/keycode-info",
      },
    ],
  },
  {
    id: "network-tools",
    title: "Network Tools",
    icon: Network,
    tools: [
      {
        id: "ipv4-subnet-calculator",
        title: "IPv4 Subnet Calculator",
        description: "Parse your IPv4 CIDR blocks and get all the info you need about your subnet.",
        icon: Network,
        path: "/network-tools/ipv4-subnet-calculator",
      },
      {
        id: "ipv4-address-converter",
        title: "IPv4 Address Converter",
        description: "Convert an IP address into decimal, binary, hexadecimal, or even an IPv6 representation of it.",
        icon: Network,
        path: "/network-tools/ipv4-address-converter",
      },
      {
        id: "ipv4-range-expander",
        title: "IPv4 Range Expander",
        description: "Given a start and an end IPv4 address, this tool calculates a valid IPv4 subnet along with its CIDR notation.",
        icon: Network,
        path: "/network-tools/ipv4-range-expander",
      },
      {
        id: "mac-address-lookup",
        title: "MAC Address Lookup",
        description: "Find the vendor and manufacturer of a device by its MAC address.",
        icon: Network,
        path: "/network-tools/mac-address-lookup",
      },
    ],
  },
  {
    id: "media-qr",
    title: "Media & QR",
    icon: QrCode,
    tools: [
      {
        id: "qr-code-generator",
        title: "QR Code Generator",
        description: "Generate and download a QR code for a URL (or just plain text), and customize the background and foreground colors.",
        icon: QrCode,
        path: "/media-qr/qr-code-generator",
      },
      {
        id: "wifi-qr-code-generator",
        title: "WiFi QR Code Generator",
        description: "Generate and download QR codes for quick connections to WiFi networks.",
        icon: Wifi,
        path: "/media-qr/wifi-qr-code-generator",
      },
      {
        id: "svg-placeholder-generator",
        title: "SVG Placeholder Generator",
        description: "Generate svg images to use as a placeholder in your applications.",
        icon: Image,
        path: "/media-qr/svg-placeholder-generator",
      },
      {
        id: "camera-recorder",
        title: "Camera Recorder",
        description: "Take a picture or record a video from your webcam or camera.",
        icon: Camera,
        path: "/media-qr/camera-recorder",
      },
    ],
  },
      {
        id: "calculators",
        title: "Calculators",
        icon: Calculator,
    tools: [
      {
        id: "math-evaluator",
        title: "Math Evaluator",
        description: "A calculator for evaluating mathematical expressions. You can use functions like sqrt, cos, sin, abs, etc.",
        icon: Calculator,
        path: "/calculators/math-evaluator",
      },
      {
        id: "eta-calculator",
        title: "ETA Calculator",
        description: "An ETA (Estimated Time of Arrival) calculator to determine the approximate end time of a task, for example, the end time and duration of a file download.",
        icon: Clock,
        path: "/calculators/eta-calculator",
      },
      {
        id: "percentage-calculator",
        title: "Percentage Calculator",
        description: "Easily calculate percentages from a value to another value, or from a percentage to a value.",
        icon: Calculator,
        path: "/calculators/percentage-calculator",
      },
      {
        id: "chronometer",
        title: "Chronometer",
        description: "Monitor the duration of a thing. Basically a chronometer with simple chronometer features.",
        icon: Timer,
        path: "/calculators/chronometer",
      },
    ],
  },
  {
    id: "other",
    title: "Other",
    icon: Settings,
    tools: [
      {
        id: "device-information",
        title: "Device Information",
        description: "Get information about your current device (screen size, pixel-ratio, user agent, ...).",
        icon: Info,
        path: "/other/device-information",
      },
      {
        id: "basic-auth-generator",
        title: "Basic Auth Generator",
        description: "Generate a base64 basic auth header from a username and password.",
        icon: ShieldCheck,
        path: "/other/basic-auth-generator",
      },
      {
        id: "open-graph-generator",
        title: "Open Graph Meta Generator",
        description: "Generate open-graph and socials HTML meta tags for your website.",
        icon: Globe2,
        path: "/other/open-graph-generator",
      },
      {
        id: "mime-types",
        title: "MIME Types",
        description: "Convert MIME types to file extensions and vice-versa.",
        icon: FileType,
        path: "/other/mime-types",
      },
      {
        id: "html-wysiwyg-editor",
        title: "HTML WYSIWYG Editor",
        description: "Online, feature-rich WYSIWYG HTML editor which generates the source code of the content immediately.",
        icon: FileCode,
        path: "/other/html-wysiwyg-editor",
      },
      {
        id: "outlook-safelink-decoder",
        title: "Outlook Safelink Decoder",
        description: "Decode Outlook SafeLink links.",
        icon: Link,
        path: "/other/outlook-safelink-decoder",
      },
      {
        id: "json-to-csv",
        title: "JSON to CSV",
        description: "Convert JSON to CSV with automatic header detection.",
        icon: FileJson,
        path: "/other/json-to-csv",
      },
      {
        id: "markdown-to-html",
        title: "Markdown to HTML",
        description: "Convert Markdown to Html and allow to print (as PDF).",
        icon: FileCode2,
        path: "/other/markdown-to-html",
      },
      {
        id: "url-encoder-decoder",
        title: "Encode/Decode URL-formatted Strings",
        description: "Encode text to URL-encoded format (also known as 'percent-encoded'), or decode from it.",
        icon: Link,
        path: "/other/url-encoder-decoder",
      },
      {
        id: "html-entities",
        title: "Escape HTML Entities",
        description: "Escape or unescape HTML entities (replace characters like <,>, &, \" and ' with their HTML version).",
        icon: Code,
        path: "/other/html-entities",
      },
      {
        id: "benchmark-builder",
        title: "Benchmark Builder",
        description: "Easily compare execution time of tasks with this very simple online benchmark builder.",
        icon: Gauge,
        path: "/other/benchmark-builder",
      },
      {
        id: "emoji-picker",
        title: "Emoji Picker",
        description: "Copy and paste emojis easily and get the unicode and code points value of each emoji.",
        icon: Smile,
        path: "/other/emoji-picker",
      },
    ],
  },
]

// Flatten all tools for easy access
export const allTools = toolCategories.flatMap((category) => category.tools)

// Get tool by path
export function getToolByPath(path: string): Tool | undefined {
  return allTools.find((tool) => tool.path === path)
}

