/**
 * Admin Types
 */

export type UserRole = "user" | "admin" | "super_admin";

export interface Profile {
  id: number;
  user_id: string;
  first_name: string;
  last_name: string;
  avatar_url: string | null;
  role: UserRole;
  terms_accepted: boolean;
  terms_accepted_at: string | null;
  created_at: string;
  updated_at: string;
  email?: string; // Joined from auth.users
}

export interface User {
  id: string;
  email: string;
  created_at: string;
}

export interface ProfileWithUser extends Profile {
  user?: User;
}

/**
 * Auth context type
 */
export interface AuthUser {
  id: string;
  email: string;
  name: string;
  role: UserRole;
}

/**
 * Portfolio Types
 */

export interface Hero {
  id: string;
  name: string;
  role: string;
  tagline: string | null;
  blurb: string | null;
  location: string | null;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface About {
  id: string;
  summary: string | null;
  personal: PersonalInfo[];
  highlights: string[];
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface PersonalInfo {
  label: string;
  value: string;
}

export interface Education {
  id: string;
  school: string;
  degree: string;
  period: string;
  location: string | null;
  detail: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface Experience {
  id: string;
  company: string;
  role: string;
  period: string;
  location: string | null;
  summary: string | null;
  bullets: string[];
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface SkillCategory {
  id: string;
  title: string;
  icon_key: string;
  color: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface Skill {
  id: string;
  category_id: string;
  name: string;
  level: number | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface SkillCategoryWithSkills extends SkillCategory {
  skills: Skill[];
}

export interface TechIcon {
  id: string;
  icon_key: string;
  name: string;
  color: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface Project {
  id: string;
  name: string;
  short_description: string | null;
  full_description: string | null;
  image_light: string | null;
  image_dark: string | null;
  tags: string[];
  github_link: string | null;
  live_link: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface Certificate {
  id: string;
  name: string;
  path: string;
  description: string | null;
  category: string | null;
  issuer: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface Contact {
  id: string;
  email: string | null;
  phone: string | null;
  location: string | null;
  socials: SocialLink[];
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export interface SocialLink {
  platform: string;
  url: string;
  icon_key: string;
}

export interface NavItem {
  id: string;
  section_id: string;
  label: string;
  icon_key: string;
  color: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Jobs Types
 */

export type JobSourceKind = "remotive" | "wwr" | "greenhouse" | "lever" | "hn_hiring";

export type JobApplicationStatus =
  | "new"
  | "interested"
  | "applied"
  | "interviewing"
  | "offer"
  | "rejected"
  | "withdrawn";

export type JobAiRecommendation =
  | "apply"
  | "apply_with_referral"
  | "apply_if_time"
  | "skip"
  | "skip_red_flags";

export type JobPriority = "low" | "medium" | "high" | "critical";

export interface JobApplicationQaItem {
  question: string;
  answer: string | null;
  category?: string;
  needs_answer?: boolean;
  created_at?: string;
  answered_at?: string | null;
  // Form-field metadata when generated by /prepare-application
  field_name?: string;
  field_type?: string;
  field_group?: "main" | "location" | "demographic" | "compliance" | "other";
  required?: boolean;
  values?: { value: string; label: string }[] | null;
  note?: string | null;
}

export interface JobSource {
  id: string;
  kind: JobSourceKind;
  label: string;
  config: Record<string, unknown>;
  is_active: boolean;
  last_fetched_at: string | null;
  last_fetch_status: string | null;
  last_fetch_error: string | null;
  last_fetch_count: number | null;
  created_at: string;
  updated_at: string;
}

export interface JobListing {
  id: string;
  source_id: string;
  external_id: string;
  title: string;
  company: string;
  location: string | null;
  is_remote: boolean;
  is_india: boolean;
  salary_text: string | null;
  salary_min_inr: number | null;
  salary_max_inr: number | null;
  salary_currency: string | null;
  description_html: string | null;
  description_text: string | null;
  apply_url: string;
  tags: string[];
  posted_at: string | null;
  fetched_at: string;
  created_at: string;
  updated_at: string;
  ai_score: number | null;
  ai_recommendation: JobAiRecommendation | null;
  ai_reasoning: string | null;
  ai_red_flags: string[];
  ai_cover_letter: string | null;
  ai_referral_message: string | null;
  ai_processed_at: string | null;
  ai_application_qa: JobApplicationQaItem[];
  // joined
  source_kind?: JobSourceKind;
  application?: JobApplication | null;
}

export interface JobApplication {
  id: string;
  listing_id: string | null;
  title: string;
  company: string;
  apply_url: string | null;
  status: JobApplicationStatus;
  priority: JobPriority;
  applied_at: string | null;
  notes: string | null;
  referral_contact: string | null;
  referral_status: string | null;
  next_action_at: string | null;
  next_action_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface JobSearchCriteria {
  id: string;
  is_active: boolean;
  keywords: string[];
  excluded_keywords: string[];
  locations: string[];
  min_salary_inr: number | null;
  remote_ok: boolean;
  created_at: string;
  updated_at: string;
}

export interface JobListingsResponse {
  data: JobListing[];
  total: number;
  page: number;
  pageSize: number;
}

export interface JobListingFilters {
  q?: string;
  india?: boolean;
  remote?: boolean;
  source_kind?: JobSourceKind | "all";
  source_id?: string;
  matches_keywords?: boolean;
  has_salary?: boolean;
  min_salary_inr?: number;
  status?: JobApplicationStatus | "none" | "all";
  ai_scored?: boolean;
  min_ai_score?: number;
  recommendation?: JobAiRecommendation | "all";
  priority?: JobPriority | "all";
  sort?: "ai_score" | "posted_at";
  page?: number;
  pageSize?: number;
}

/**
 * Vercel Types
 */

export type VercelDeploymentState =
  | "BUILDING"
  | "ERROR"
  | "INITIALIZING"
  | "QUEUED"
  | "READY"
  | "CANCELED";

export type VercelTarget = "production" | "preview" | null;

export interface VercelDeployment {
  uid: string;
  name: string;
  url: string;
  created: number;
  state: VercelDeploymentState;
  target: VercelTarget;
  meta?: {
    githubCommitSha?: string;
    githubCommitMessage?: string;
    githubCommitRef?: string;
    githubCommitAuthorName?: string;
  };
  creator?: {
    uid: string;
    username: string;
  };
  inspectorUrl?: string;
  ready?: number;
  buildingAt?: number;
}

export interface VercelDeploymentDetail extends VercelDeployment {
  readyState: VercelDeploymentState;
  aliasAssigned?: number;
  aliasError?: { code: string; message: string } | null;
  regions: string[];
  routes?: unknown[];
  plan: string;
  projectId: string;
}

export interface VercelBuildLogEntry {
  type: "stdout" | "stderr" | "command" | "delimiter";
  created: number;
  payload: string;
}

export type VercelEnvTarget = "production" | "preview" | "development";

export interface VercelEnvVar {
  id: string;
  key: string;
  value: string;
  type: "system" | "encrypted" | "plain" | "secret" | "sensitive";
  target: VercelEnvTarget[];
  configurationId?: string | null;
  createdAt?: number;
  updatedAt?: number;
}

export type VercelProjectKey = "jg" | "admin";

/**
 * Blog Types
 */

export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  cover_image: string | null;
  tags: string[];
  is_visible: boolean;
  is_published: boolean;
  published_at: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}
