import type { PortfolioTable } from "./portfolio";

/** Columns generated by the database and therefore forbidden in write input. */
export const PORTFOLIO_GENERATED_KEYS = [
  "id",
  "created_at",
  "updated_at",
] as const;

/** Explicit writable-column allowlist for every Portfolio CMS table. */
export const PORTFOLIO_WRITE_KEYS: Record<PortfolioTable, readonly string[]> = {
  hero: [
    "role",
    "tagline",
    "blurb",
    "headline",
    "current_title",
    "availability",
    "resume_url",
    "github_username",
    "seo_description",
  ],
  about: [
    "summary",
    "personal",
    "headline",
    "objective",
    "story",
    "principles",
  ],
  education: [
    "school",
    "degree",
    "period",
    "location",
    "detail",
    "sort_order",
    "is_visible",
  ],
  experience: [
    "company",
    "company_url",
    "company_linkedin_url",
    "role",
    "period",
    "location",
    "summary",
    "bullets",
    "sort_order",
    "is_visible",
  ],
  skill_categories: ["title", "description", "sort_order", "is_visible"],
  skills: [
    "category_id",
    "name",
    "proficiency",
    "evidence",
    "sort_order",
    "is_visible",
  ],
  work: [
    "name",
    "short_description",
    "tags",
    "github_link",
    "live_link",
    "slug",
    "eyebrow",
    "impact",
    "contribution",
    "year_label",
    "image_url",
    "image_alt",
    "case_study",
    "case_study_published",
    "sort_order",
    "is_visible",
  ],
  certificates: [
    "name",
    "description",
    "category",
    "issuer",
    "issued_at",
    "credential_id",
    "credential_url",
    "document_url",
    "preview_url",
    "image_alt",
    "sort_order",
    "is_visible",
  ],
  contact: ["email", "phone", "location", "socials"],
  nav_items: ["section_id", "label", "note", "sort_order", "is_visible"],
  section_content: [
    "section_key",
    "eyebrow",
    "headline",
    "accent",
    "description",
    "supporting_text",
    "is_visible",
  ],
};

/** Fields that must be present when Admin creates a Portfolio record. */
export const PORTFOLIO_REQUIRED_CREATE_KEYS: Partial<
  Record<PortfolioTable, readonly string[]>
> = {
  hero: [
    "role",
    "tagline",
    "blurb",
    "headline",
    "current_title",
    "availability",
    "resume_url",
    "github_username",
    "seo_description",
  ],
  about: ["summary", "headline", "objective"],
  education: ["school", "degree", "period"],
  experience: ["company", "role", "period"],
  skill_categories: ["title", "description"],
  skills: ["category_id", "name", "proficiency", "evidence"],
  work: [
    "name",
    "short_description",
    "slug",
    "eyebrow",
    "impact",
    "contribution",
    "year_label",
    "image_url",
    "image_alt",
  ],
  certificates: [
    "name",
    "category",
    "issuer",
    "document_url",
    "preview_url",
    "image_alt",
  ],
  contact: ["email", "phone", "location"],
  nav_items: ["section_id", "label"],
  section_content: ["section_key", "eyebrow"],
};

/** URL-bearing fields that receive shared public URL validation. */
export const PORTFOLIO_URL_KEYS: Partial<
  Record<PortfolioTable, readonly string[]>
> = {
  hero: ["resume_url"],
  experience: ["company_url"],
  work: ["image_url", "github_link", "live_link"],
  certificates: ["credential_url", "document_url", "preview_url"],
};
