-- =============================================================================
-- Migration: Create jg_account schema with unified profiles table
-- Date: 2025-02-11
-- Description: Replaces portfolio.profile + auth.users.user_metadata with a
--   single jg_account.profiles table used by both main app and admin app.
-- =============================================================================

-- Schema
CREATE SCHEMA IF NOT EXISTS jg_account;

-- Enum: user roles
CREATE TYPE jg_account.user_role AS ENUM ('user', 'admin', 'super_admin');

-- Table: profiles
CREATE TABLE jg_account.profiles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID UNIQUE NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  first_name  TEXT NOT NULL DEFAULT '',
  last_name   TEXT NOT NULL DEFAULT '',
  avatar_url  TEXT,
  role        jg_account.user_role NOT NULL DEFAULT 'user',
  terms_accepted    BOOLEAN NOT NULL DEFAULT FALSE,
  terms_accepted_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON jg_account.profiles (user_id);

-- Grants
GRANT USAGE ON SCHEMA jg_account TO anon, authenticated, service_role;
GRANT ALL ON jg_account.profiles TO anon, authenticated, service_role;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA jg_account TO anon, authenticated, service_role;

-- Trigger: auto-update updated_at
CREATE OR REPLACE FUNCTION jg_account.handle_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON jg_account.profiles
  FOR EACH ROW EXECUTE FUNCTION jg_account.handle_updated_at();

-- Trigger: auto-create profile on new user signup
CREATE OR REPLACE FUNCTION jg_account.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  INSERT INTO jg_account.profiles (user_id, first_name, last_name, terms_accepted, terms_accepted_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'first_name', ''),
    COALESCE(NEW.raw_user_meta_data ->> 'last_name', ''),
    COALESCE((NEW.raw_user_meta_data ->> 'terms_accepted')::boolean, FALSE),
    CASE
      WHEN (NEW.raw_user_meta_data ->> 'terms_accepted')::boolean = TRUE
      THEN COALESCE((NEW.raw_user_meta_data ->> 'terms_accepted_at')::timestamptz, now())
      ELSE NULL
    END
  );
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'jg_account.handle_new_user failed for user %: %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION jg_account.handle_new_user();

-- Helper function
CREATE OR REPLACE FUNCTION jg_account.is_admin()
RETURNS BOOLEAN LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM jg_account.profiles
    WHERE user_id = auth.uid() AND role IN ('admin', 'super_admin')
  );
END;
$$;

-- RLS
ALTER TABLE jg_account.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own profile" ON jg_account.profiles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can update own profile" ON jg_account.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id AND role = (SELECT role FROM jg_account.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Admins can read all profiles" ON jg_account.profiles
  FOR SELECT TO authenticated USING (jg_account.is_admin());

CREATE POLICY "Super admins can update any profile" ON jg_account.profiles
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM jg_account.profiles WHERE user_id = auth.uid() AND role = 'super_admin'));

CREATE POLICY "Super admins can insert profiles" ON jg_account.profiles
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM jg_account.profiles WHERE user_id = auth.uid() AND role = 'super_admin'));

CREATE POLICY "Super admins can delete profiles" ON jg_account.profiles
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM jg_account.profiles WHERE user_id = auth.uid() AND role = 'super_admin'));
